version: '3.8'

services:
  php:
    container_name: laravel-project-php
    hostname: laravel-project-php
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./supervisor/log:/var/log/supervisor
    networks:
      - laravel-project-php

  nginx:
    container_name: laravel-project-nginx
    hostname: laravel-project-nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravel-project-php

  postgres:
    container_name: laravel-project-database
    hostname: laravel-project-database
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - laravel-project-php

  redis:
    container_name: laravel-project-redis
    hostname: laravel-project-redis
    image: redis:latest
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    #Open port to public is optional, I usually connect with backend service like php service on up check conf file
#    ports:
#      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - laravel-project-php

  rabbitmq:
    # default management login guest:guest
    container_name: laravel-project-rabbitmq
    hostname: laravel-project-rabbitmq
    image: rabbitmq:4.0.5-management
    ports:
      - "15672:15672"
    networks:
      - laravel-project-php
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongo:
    image: mongo
    container_name: laravel-project-mongo
    hostname: laravel-project-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/etc/mongo
    networks:
      - laravel-project-php

networks:
  laravel-project-php:
    name: laravel-project-php
    driver: bridge

volumes:
  postgres:
  redis_data:
  rabbitmq_data:
  mongodb_data:
